# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bluetooth.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1063, 506)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 221, 351))
        self.groupBox.setObjectName("groupBox")
        self.Accel_x = QtWidgets.QCheckBox(self.groupBox)
        self.Accel_x.setGeometry(QtCore.QRect(40, 60, 92, 25))
        self.Accel_x.setObjectName("Accel_x")
        self.Accel_y = QtWidgets.QCheckBox(self.groupBox)
        self.Accel_y.setGeometry(QtCore.QRect(40, 90, 92, 25))
        self.Accel_y.setObjectName("Accel_y")
        self.Accel_z = QtWidgets.QCheckBox(self.groupBox)
        self.Accel_z.setGeometry(QtCore.QRect(40, 120, 92, 25))
        self.Accel_z.setObjectName("Accel_z")
        self.Gyro_z = QtWidgets.QCheckBox(self.groupBox)
        self.Gyro_z.setGeometry(QtCore.QRect(30, 270, 92, 25))
        self.Gyro_z.setObjectName("Gyro_z")
        self.Gyro_all = QtWidgets.QCheckBox(self.groupBox)
        self.Gyro_all.setGeometry(QtCore.QRect(10, 180, 92, 25))
        self.Gyro_all.setObjectName("Gyro_all")
        self.Gyro_x = QtWidgets.QCheckBox(self.groupBox)
        self.Gyro_x.setGeometry(QtCore.QRect(30, 210, 92, 25))
        self.Gyro_x.setObjectName("Gyro_x")
        self.Gyro_y = QtWidgets.QCheckBox(self.groupBox)
        self.Gyro_y.setGeometry(QtCore.QRect(30, 240, 92, 25))
        self.Gyro_y.setObjectName("Gyro_y")
        self.Accel_all = QtWidgets.QCheckBox(self.groupBox)
        self.Accel_all.setGeometry(QtCore.QRect(10, 30, 92, 25))
        self.Accel_all.setObjectName("Accel_all")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(300, 70, 701, 331))
        self.widget.setObjectName("widget")

        self.Accel_all.setChecked(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.Accel_x.setText(_translate("Form", "Accel, x"))
        self.Accel_y.setText(_translate("Form", "Accel, y"))
        self.Accel_z.setText(_translate("Form", "Accel, z"))
        self.Gyro_z.setText(_translate("Form", "Gyro, z"))
        self.Gyro_all.setText(_translate("Form", "Gyro all"))
        self.Gyro_x.setText(_translate("Form", "Gyro, x"))
        self.Gyro_y.setText(_translate("Form", "Gyro, y"))
        self.Accel_all.setText(_translate("Form", "Accel all"))
