# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab1_4.5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1125, 486)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 88, 27))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: green; border-radius: 5px; color: white; font-weight: bold;")
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 191, 251))
        self.groupBox.setObjectName("groupBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(20, 50, 151, 28))
        self.spinBox.setSuffix("")
        self.spinBox.setPrefix("")
        self.spinBox.setMaximum(1000)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(20, 130, 151, 28))
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setGeometry(QtCore.QRect(20, 210, 151, 28))
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setProperty("value", 20)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 161, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 151, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 161, 19))
        self.label_3.setObjectName("label_3")
        self.MplWidget = MplWidget(Form)
        self.MplWidget.setGeometry(QtCore.QRect(240, 30, 851, 421))
        self.MplWidget.setObjectName("MplWidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 370, 191, 41))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Table_button = QtWidgets.QPushButton(Form)
        self.Table_button.setGeometry(QtCore.QRect(10, 420, 191, 27))
        self.Table_button.setObjectName("Table_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.label.setText(_translate("Form", "Measurement interval"))
        self.label_2.setText(_translate("Form", "X-axis interval"))
        self.label_3.setText(_translate("Form", "Measurement duration"))
        self.plainTextEdit.setPlaceholderText(_translate("Form", "Give a filename for table..."))
        self.Table_button.setText(_translate("Form", "Make table"))
from mplwidget import MplWidget
